#!/bin/bash
jupyter labextension install @jupyterlab/katex-extension @agoose77/jupyterlab-markup bqplot @jupyter-widgets/jupyterlab-manager
echo "application/wasm      wasm" | sudo tee -a /etc/mime.types