#!/usr/bin/env bash
declare -a extensions=(
  "@jupyter-widgets/jupyterlab-manager"
  "@agoose77/jupyterlab-markup"
  "@jupyterlab/katex-extension"
  bqplot
)

jupyter labextension install "${extensions[@]}"

grep "application/wasm" /etc/mime.types || echo "application/wasm      wasm" | sudo tee -a /etc/mime.types