#!/bin/bash

# Get the right workspace ID
sed -i -e "s|WORKSPACE_ID|/user/${JUPYTERHUB_USER}/lab|g" main-workspace.json

# Import the workspace into JupyterLab
jupyter lab workspaces import main-workspace.json \
  --NotebookApp.base_url=user/${JUPYTERHUB_USER}

exec "$@"